version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=express-ts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    depends_on: 
      db:
        condition: service_healthy
    environment:
      - POSTGRES_DB=express-ts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db

  proxy:
    restart: always
    build: ../django_backend
    depends_on: 
      - app
    expose:
      - 8080
    ports:
      - "8080:8080"
    command: /usr/local/bin/mitmdump --mode reverse:http://app:8000
    
volumes:
  pgdata:
