version: '3'

services:
  web:
    restart: always
    build: .
    links:
      - postgres:postgres
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file: .env
    environment:
      DEBUG: 'true'
    ports:
      - "5000:5000"
    command: /usr/local/bin/gunicorn wsgi:application -w 2 -b :5000
    networks:
      - my_network

  postgres:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  web-django:
  web-static:
  pgdata:

networks:
  my_network:
    driver: bridge